StartupEvents.registry("block", (event) => {
    
	event.create("primitive_machine") // Create a new block
    .displayName("Primitive Machine Casing") // Set a custom name
    .soundType("stone") // Set a material (affects the sounds and some properties)
    .hardness(1.0) // Set hardness (affects mining time)
    .resistance(4.0) // Set resistance (to explosions, etc)
    .tagBoth("tier1/component") // Tag the block with `#minecraft:my_custom_tag` (can have multiple tags)
    .requiresTool(true) // Requires a tool or it won't drop (see tags below)
    .tagBlock("mineable/pickaxe") // or a pickaxe
    .tagBlock('minecraft:needs_stone_tool') // the tool tier must be at least iron
	
	
	event.create("basic_magic_machine") 
    .displayName("Basic Magic Machine")
    .soundType("amethyst") 
    .hardness(1.0)
    .resistance(6.0) 
    .tagBoth("tier1/component")
    .requiresTool(true)
    .tagBlock("mineable/pickaxe") 
    .tagBlock('minecraft:needs_stone_tool') 
	.texture('up', 'kubejs:block/basic_magic_machine_top')
	.texture('down', 'kubejs:block/basic_magic_machine_top')
	

    event.create("magical_generator_block") 
    .soundType("amethyst") 
    .hardness(1.0) 
    .resistance(6.0) 
    .tagBoth("tier2/component") 
    .requiresTool(true) 
    .tagBlock("mineable/pickaxe") 
    .tagBlock('minecraft:needs_iron_tool') 

    event.create("aura_generator_block") 
    .soundType("amethyst") 
    .hardness(1.0) 
    .resistance(6.0) 
    .tagBoth("tier2/component") 
    .requiresTool(true) 
    .tagBlock("mineable/pickaxe") 
    .tagBlock('minecraft:needs_iron_tool')
	
	event.create("magic_machine") 
    .displayName("Magic Machine") 
    .soundType("amethyst")
    .hardness(1.2) 
    .resistance(6.0) 
    .tagBoth("tier2/component")
    .requiresTool(true) 
    .tagBlock("mineable/pickaxe") 
    .tagBlock('minecraft:needs_iron_tool') 
	.texture('up', 'kubejs:block/magic_machine_top')
	.texture('down', 'kubejs:block/magic_machine_top')
	
	
	
	event.create("andesite_machine") 
    .displayName("Andesite Machine Casing") 
    .soundType("metal") 
    .hardness(1.0) 
    .resistance(8.0) 
    .tagBoth("tier3/component") 
    .requiresTool(true) 
    .tagBlock("mineable/pickaxe") 
    .tagBlock('minecraft:needs_iron_tool') 
	.texture('up', 'kubejs:block/andesite_machine_top')
	.texture('down', 'kubejs:block/andesite_machine_bot')
	

    event.create("pressing_catalyst","falling")
    .displayName("Pressing Catalyst") 
    .soundType("anvil") 
    .hardness(1.5) 
    .resistance(8.0) 
    .tagBoth("tier2/component") 
    .requiresTool(true) 
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool') 
	.texture('up', 'kubejs:block/anvil')
	.texture('down', 'kubejs:block/anvil')
	
	
	event.create("steel_machine") 
    .displayName("Steel Machine Casing") 
    .soundType("anvil") 
    .hardness(3.0) 
    .resistance(12.0) 
    .tagBoth("tier4/component") 
    .requiresTool(true) 
    .tagBlock("mineable/pickaxe") 
    .tagBlock('minecraft:needs_iron_tool') 
	.texture('up', 'kubejs:block/steel_machine_top')
	.texture('down', 'kubejs:block/steel_machine_bot')
	

    event.create("gold_leaf_block")
    .displayName("Gold Leaf Block")
    .soundType("moss")
    .hardness("0.2")
    .resistance("0.5")
    .tagBlock("mineable/hoe")

    event.create("ivy_block","basic")
    .displayName("Ivy Block")
    .soundType("moss")
    .hardness("0.2")
    .resistance("0.5")
    .tagBlock("mineable/hoe")
    .tagBlock("minecraft:climbable")

    event.create("sturdy_deepslate")
    .textureAll("minecraft:block/blast_furnace_top")
    .displayName("Sturdy Deepslate")
    .soundType("polished_deepslate")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")

    event.create("sturdy_deepslate_slab","slab")
    .textureAll("minecraft:block/blast_furnace_top")
    .soundType("polished_deepslate")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")

    event.create("sturdy_deepslate_plate")
    .textureAll("minecraft:block/blast_furnace_top")
    .box(0, 0, 0, 16, 3, 16)
    .soundType("polished_deepslate")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")

    event.create("deepslate_rune","cardinal")
    .model('kubejs:block/deepslate_rune')
    .box(2, 0, 0, 9, 3, 1)
    .box(1, 0, 1, 10, 3, 4)
    .box(5, 0, 4, 13, 3, 16)
    .box(0, 0, 4, 5, 3, 11)
    .box(10, 0, 2, 11, 3, 4)
    .box(13, 0, 5, 10, 3, 8)
    .box(14, 0, 7, 15, 3, 8)
    .box(13, 0, 12, 15, 3, 14)
    .box(13, 0, 14, 14, 3, 15)
    .box(2, 0, 11, 5, 3, 13)
    .box(1, 0, 11, 2, 3, 12)
    .box(4, 0, 13, 5, 3, 15)
    .box(13, 0, 5, 14, 3, 8)
    .box(13, 0, 8, 16, 3, 12)
    .renderType('cutout')
    .soundType("polished_deepslate")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")

    event.create("broken_spawner")
    .textureAll("minecraft:block/spawner")
    .displayName("Broken Spawner")
    .soundType("stone")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")

    event.create("polished_planks")
    .textureAll("minecraft:block/beehive_end")
    .displayName("Polished Planks")
    .soundType("wood")
    .hardness("1")
    .resistance("3")
    .tagBlock("mineable/axe")

    event.create("stacked_planks")
    .textureAll("minecraft:block/composter_side")
    .displayName("Stacked Planks")
    .soundType("wood")
    .hardness("1")
    .resistance("3")
    .tagBlock("mineable/axe")

    event.create("packed_planks")
    .textureAll("minecraft:block/composter_bottom")
    .displayName("Packed Planks")
    .soundType("wood")
    .hardness("1")
    .resistance("3")
    .tagBlock("mineable/axe")

    event.create("sturdy_basalt")
    .textureAll("rubinated_nether:block/freezer/freezer_bottom")
    .displayName("Copper Reinforced Sturdy Basalt")
    .soundType("gilded_blackstone")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')

    event.create("inert_alloy_block")
    .soundType("metal")
    .hardness("2")
    .resistance("6")
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')

    event.create("arcane_alloy_block")
    .soundType("metal")
    .hardness("2")
    .resistance("6")
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')

    event.create("charged_copper_block")
    .soundType("copper")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_stone_tool')

    event.create("depleted_ruby_block")
    .soundType("amethyst")
    .unbreakable()

    event.create("sapphire_block")
    .soundType("amethyst")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')
    
    event.create("infusing_altar")
    .soundType("basalt")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')
    .textureAll("rubinated_nether:block/altar_stone")
    .renderType('cutout')
    .box(0,0,0,16,3,16)
    .box(0,3,0,2,6,16)
    .box(0,3,0,16,6,2)
    .box(14,3,0,16,6,16)
    .box(0,3,14,16,6,16)

    event.create("blasting_altar")
    .soundType("basalt")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')
    .textureAll("immersiveengineering:block/stone_decoration/blastbrick_reinforced")
    .renderType('cutout')
    .box(0,0,0,16,3,16)
    .box(0,3,0,2,6,16)
    .box(0,3,0,16,6,2)
    .box(14,3,0,16,6,16)
    .box(0,3,14,16,6,16)

    event.create("alloying_altar")
    .soundType("basalt")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')
    .textureAll("immersiveengineering:block/stone_decoration/alloybrick")
    .renderType('cutout')
    .box(0,0,0,16,3,16)
    .box(0,3,0,2,6,16)
    .box(0,3,0,16,6,2)
    .box(14,3,0,16,6,16)
    .box(0,3,14,16,6,16)

    event.create("sacrificial_altar")
    .soundType("basalt")
    .hardness("3")
    .resistance("6")
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')
    .textureAll("minecraft:block/polished_blackstone")
    .renderType('cutout')
    .box(0,0,0,16,3,16)
    .box(0,3,0,2,6,16)
    .box(0,3,0,16,6,2)
    .box(14,3,0,16,6,16)
    .box(0,3,14,16,6,16)

    

	
})